import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetbrainsMono NerdFont", style = "Medium" }
bold = { family = "JetBrainsMono"}
size = 12.0


[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
